@isTest
private class ScheduledDealPointsRollup_Test {
	//public static String CRON_EXP = '0 0 * * * ? *';
	
 //   static testMethod void myUnitTest() {
 //       Test.startTest();
 //       	String jobId = System.schedule('testScheduledDealPointsRollup', CRON_EXP, new ScheduledDealPointsRollup());
        	
 //       // Get the information from the CronTrigger API object
	//      CronTrigger ct = [SELECT id, CronExpression, TimesTriggered, NextFireTime
	//						FROM CronTrigger WHERE id = :jobId];
	
	//   // Verify the expressions are the same
	//      System.assertEquals(CRON_EXP, ct.CronExpression);
	
	//   // Verify the job has not run
	//      System.assertEquals(0, ct.TimesTriggered);
	//	Test.stopTest();
 //   }
}