0,Common End-user Software,
1,Administrative or Clerical,
4,CAD/CAM,
5,Engineering,
6,Environmental,
7,Finance,
9,Human Resources,
10,Information Technology,
11,General Non-Skilled Labor,
12,Legal,
13,Manufacturing,
14,Marketing,
15,Scientific,
16,Telecommunications,
19,Insurance,
20,Sales,
21,Aviation,
22,Construction Non-Laborer,
26,Power Engineering,
27,Light Technical/Trades/Skilled Labor,
28,Clinical,
29,Hardware Engineering,
31,Technical Writing,
32,Degreed Accounting,
33,Graphic Design,
34,Business Operations and General Business,
36,Travel,
37,Recruiting,
43,Distribution and Shipping,
44,Petrochemical,
45,Transmission & Distribution,
46,Call Center or Help Desk or Customer Service,
64,Training,
66,Facilities,
67,Business Development,
68,Entry Level,
69,QA and QC,
70,Research,
71,Strategy and Planning,
72,"Installation, Maintenance, Repair",
73,Grocery,
74,Biotech/Life Sciences,
75,Pharmaceutical,
76,"Broadcasting, Journalism",
77,Education,
78,Retail,
79,"Restaurant, Food Service",
80,General Management,
81,Banking and Related,
82,Hotel and Hospitality,
83,Legal Admin and Clerical,
84,Transportation,
85,Architecture,
86,Government,
87,Warehouse,
89,"Bookkeeping, Office Management",
90,Personal Attributes,
91,Translations and Language Work,
92,Knowledge and Learning Management,
94,Physician and NonNursing/NonAdmin,
95,Healthcare Non-physician Non-nurse,
96,Executive,
97,"Purchasing, Procurement, Inventory Control, Supply Chain",
98,Security,
99,Nursing,
485,Gauges,23
108,Core Office,0
228,Data Centric,0
229,Visual,0
230,Planning and Analysis,0
231,Contact Mgmt,0
232,Other,0
299,Operating Systems,0
300,Mac,0
109,"Stenography, Typing, Filing",1
110,Billing and Collections,1
111,Recordkeeping and Supplies,1
112,Messages and Contact,1
113,Admin,1
114,Closing and Processing,1
115,Computer Related,1
116,Contracts,1
117,Accounting Related,1
118,Clerk,1
119,Special Events,1
499,Entry Level,1
945,Machines,1
356,Architectural,4
357,Engineering,4
358,Other,4
132,Chemical,5
133,Civil,5
134,Design,5
135,Electrical,5
136,Environmental,5
137,Industrial,5
138,Mechanical,5
139,Network,5
140,Nuclear,5
141,Optical,5
142,Plant,5
143,Process,5
144,Computer Hardware,5
145,Structural,5
146,Telecom,5
263,Other,5
264,Techniques,5
265,Technologies,5
266,Circuits,5
267,Military,5
268,RF,5
296,Water Wastewater Soil Hydology,5
297,Transportation,5
298,Surveying,5
306,Certifications,5
307,General Engineering,5
308,Power Engineering,5
309,Stress Analysis and Testing,5
310,ENG Software and Tools,5
311,Air and Aerospace,5
312,Refrigeration,5
328,"Testing, Assessments, and Monitoring",6
329,Air,6
330,Water,6
331,Soil,6
332,"Remediation, Mitigation, Cleanup, Removal",6
333,General,6
334,Hazmat,6
335,"Compliance, Licensing, Certifications",6
336,Permitting,6
337,Safety,6
233,Mortgage,7
234,Lending,7
235,Analysis,7
236,Securities,7
237,Operations,7
238,Equities,7
239,Trading,7
240,Credit and Underwriting,7
241,Management,7
242,Admin and Customer Service,7
243,Other,7
244,Broker,7
245,Compliance,7
246,Treasury,7
247,Collections,7
182,Administration,9
183,Benefits,9
184,Compensation,9
185,Payroll,9
186,Consulting,9
187,Employee Relations,9
188,Management,9
189,Operations,9
190,Recruitment,9
258,Compliance,9
259,Software,9
260,Training,9
261,Vendor Mgmt,9
262,Other,9
191,AS/400,10
192,Data Mining,10
193,Database,10
194,Help Desk,10
195,ERP and CRM,10
196,Internet,10
197,Mainframe,10
198,Network,10
199,Project Management,10
200,QA and QC,10
201,Architecture,10
202,Training,10
203,UNIX and LINUX,10
204,Programming,10
251,Config Deploy Upgrade Migrate,10
252,Prebuilt Software,10
253,Protocols and Standards,10
338,Security,10
339,Java,10
340,Embedded and Realtime,10
341,Reporting,10
342,Workflow and Imaging,10
343,Mail,10
344,GIS,10
345,Middleware and Integration,10
346,Messaging,10
347,Telephony,10
348,Service Providers,10
349,"Operations, Monitoring and Software Management",10
350,Financial,10
351,Multimedia,10
352,Content Management,10
353,Medical,10
354,SOX,10
355,Search,10
301,Drivers,11
302,Maintenance and Cleaning,11
303,Construction Labor,11
304,Non-Construction Labor,11
305,Warehouse and Picking,11
395,Intellectual Property,12
396,Contracts,12
397,Clerical,12
398,Admin,12
399,Real Estate,12
400,Litigation,12
401,Collections,12
403,Corporate Finance,12
404,Other,12
205,Cleanroom,13
206,"Machining, Metalworking, Tool and Die",13
207,Process Control,13
208,Planning,13
209,Logistics,13
210,Management,13
362,General,13
363,Air and Aerospace,13
364,Equipment,13
365,Printing,13
405,Software,13
479,Chemical,13
480,Composites,13
220,Consumer,14
221,B2B,14
222,Direct,14
223,Market Research,14
224,PR,14
225,Product Oriented,14
226,Channel Management,14
227,Brand Management,14
249,General,14
250,Events,14
372,Pharma,15
373,Bio,15
374,Animal,15
375,Clinical,15
376,Basic,15
377,Chemical,15
378,Imaging,15
313,Wireless,16
314,Cell Sites and Towers,16
315,Cabling and Related,16
316,Central Office,16
317,"Standards, Protocols, Technologies",16
318,Network,16
319,Hardware,16
320,Software,16
321,Power,16
322,Labor,16
323,Skilled,16
406,Property and Casualty,19
407,Life,19
408,Claims and Adjusting,19
409,Health,19
410,Commercial,19
411,Management,19
412,Admin and Clerical,19
413,Techniques,19
414,Other,19
415,Sales,19
416,Auto,19
100,Inside Sales,20
101,Outside Sales,20
102,Direct Sales,20
103,Channel Management,20
104,Account Management,20
105,General,20
106,Management,20
107,Presales,20
248,Telemarketing,20
500,Entry Level,20
930,Retail,20
380,Estimating,22
381,Supervision,22
382,Inspections,22
383,Safety,22
384,Commercial,22
385,Residential,22
386,Industrial,22
387,Municipal,22
388,Transportation,22
389,General Tasks and Equipment,22
390,Design,22
391,Automation,22
392,Compliance,22
393,Civil,22
394,"Office, Admin and Clerical",22
23,Nuclear Generation,26
24,DOE Facilities,26
25,Non-nuclear Generation,26
923,Nuclear Misc,26
924,Non-Nuclear Power Misc,26
925,General Power Related,26
283,Union,27
284,Welding Soldering Brazing Cutting,27
285,Hvac and Refrig,27
286,Carpentry and Painting,27
287,Machine Shop,27
288,Fine Assembly,27
289,Printing,27
290,Maint and Repair,27
291,Electrical,27
292,Moving Equipment,27
293,Other,27
294,Electronic,27
295,Piping,27
379,Assembly,27
426,Other Construction Trades,27
269,Claims and Billing,28
270,Coding,28
271,Analysis,28
272,Admin,28
273,Certifications,28
274,Research,28
275,Trials,28
276,Tests and Functions,28
277,Other,28
278,Regulatory,28
427,Software,31
428,Training,31
429,Specs and Documentation,31
430,General,31
431,Proposals and Related,31
254,Software,32
255,Tax,32
256,Other,32
257,Reconciliations,32
932,Accounting,32
933,Accounts Payable,32
940,Accounts Receivable,32
942,Auditing,32
943,Other,32
944,Bookkeeping,32
950,CPA,32
951,Consulting,32
952,Cost Accounting,32
960,Management,32
961,Payroll,32
962,Reporting,32
432,Software,33
433,Techniques and Activities,33
435,"Technical, Blueprints and Schematics",33
436,Management Activities or Functions,34
437,General Skills and Activities,34
487,Travel Software,36
488,Travel Related,36
489,Recruiting Software,37
490,Recruiting Functions,37
492,Recruiting Tasks and Activities,37
493,Executive Recruiting,37
494,IT Recruiting,37
438,Equipment,44
439,Standards,44
440,Activities,44
441,Drilling,44
442,Refining,44
443,Software,44
444,General,44
324,Overhead,45
325,Substation,45
326,Transmission,45
327,Other,45
128,Call Center,46
129,Help Desk,46
130,Customer Facing,46
131,Management,46
279,Other,46
359,Computer-Based,64
360,One On One,64
361,Other,64
445,Standards,69
446,Techniques,69
447,DT,69
448,NDT,69
931,Software,69
934,Manufacturing,69
941,Other,69
963,Research and Development,70
501,Modeling,71
502,Planning and Estimating,71
449,IT Related,72
450,Preventative,72
451,General Installation,72
452,General Repair,72
600,Agricultural Economics,74
601,Allergies and Asthma,74
602,Animal Anatomy,74
603,Aquatic Biodiversity,74
604,Avian External Anatomy,74
605,Biochemistry,74
606,Biodiversity,74
607,General,74
608,Food Agriculture,74
609,Botany,74
610,Cell Biology,74
612,Ecology,74
613,Evolution,74
614,Fish Environmentalism,74
615,Fish Terminology,74
616,General Avian,74
617,Genetics,74
618,Geology,74
619,Integrated Pest Management,74
620,History Of Life,74
621,Life Sciences,74
622,Medical Equipment and Drug Manufacturers,74
623,"Medical Equipment, Implants, Devices, Drugs, Procedures",74
624,Nanotechnology,74
625,Oncology,74
626,Paleology,74
627,Pesticides,74
628,Pharmacogenomics and Toxicogenomics,74
629,Phylogenetics,74
630,Soil Science,74
631,Tree Of Life,74
632,Zoology,74
453,Drug,75
454,Non-Drug,75
611,Drug Discovery,75
503,Recordkeeping,77
504,Curricula,77
505,Positions,77
506,Activities and Tasks,77
507,Programs and Projects,77
211,Planning,78
212,Store Management,78
213,Buyer,78
214,Area Management,78
215,General Management,78
216,HR,78
217,Safety and Loss Prevention,78
218,Operations,78
219,Sales,78
508,POS Systems,78
509,Money Handling,78
510,Types,78
511,Positions,78
516,Budget Related,80
517,People Oriented,80
518,Operations and Admin,80
519,Management and Management Tasks,80
120,Teller,81
121,Credit,81
122,Lending,81
123,Loan Operations,81
124,Check Operations,81
125,Trust,81
126,Cash Mgmt,81
127,Trading,81
280,Retail,81
281,Trust,81
282,Other,81
172,Banquet,82
173,Conventions,82
174,Concierge,82
175,Culinary and Kitchen,82
176,Front Desk,82
177,Front Office,82
178,Management,82
179,Housekeeping,82
180,Restaurant and Bar,82
181,Room Service,82
512,Cooking and Food,82
513,Management,82
514,Food Industry Classifications,82
515,Safety Health and Sanitation,82
467,Software,85
468,Certs,85
469,Urban Planning,85
470,Commercial and Industrial,85
471,Site,85
472,Structure Subparts,85
473,General,85
474,Residential and Interior Design,85
475,Civil,85
476,Landscape,85
477,Structural,85
522,Security Clearances,86
523,Procurement,86
524,Regulatory,86
495,Warehouse Manual Labor,87
496,Warehouse Related,87
497,General Tasks,87
498,Shipping,87
533,Bookeeping Tasks,89
534,Office Tasks,89
535,Payroll Tasks,89
536,Bookeeping Software,89
528,Attitude,90
529,Languages,90
531,Driver Licensing,90
532,Aptitudes,90
901,Translation,91
902,Semantics,91
903,Knowledge and Learning Management,92
157,Administration,95
158,Allied Health,95
159,Sanitation and Sterilization,95
160,Ombudsman,95
161,Environmental Services,95
162,Facilities/Plant/Maintenance,95
163,Food and Nutrition,95
164,HR,95
165,Operations,95
166,Research,95
167,Resource and Materials Management,95
168,Safety and Security,95
169,Social Work,95
170,Marketing,95
171,Support Services,95
147,CEO,96
148,CFO,96
149,CIO,96
150,COO,96
151,CTO,96
152,Controller,96
153,Director,96
154,Managing Director,96
155,President,96
156,Other,96
964,CXO,96
965,CLO,96
966,CCO,96
967,CAO,96
968,CSO,96
969,CQO,96
458,Purchasing,97
459,Inventory,97
460,Logistics,97
461,Supply Chain,97
462,Government Clearance,98
463,IT,98
464,Disaster,98
465,Physical,98
466,"Financial, Accounting and Processes",98
366,Phlebotomy,99
367,Acute,99
368,Pediatric,99
369,Oncology,99
370,Dental,99
371,Radiology,99
417,Admin,99
418,"CPR, EMT and First Aid",99
419,Long Term,99
420,Pain,99
421,Billing and Coding,99
422,Nurse Asst,99
423,Educator,99
424,Cardio,99
425,Blood and Circulatory,99
455,Other Asst,99
456,Nursing Vocations and Certs,99
457,Techniques,99
