@isTest(SeeAllData=true)
public class Test_AccountFundSummary {
	static testMethod void mytest() {
        //list<AccountFuncdSummary2Wrapper> afsList= new List<AccountFuncdSummary2Wrapper>();
        //AccountFuncdSummary2Wrapper afsItem = new AccountFuncdSummary2Wrapper();
        
        //afsList.add(afsItem);
        //AccountFuncdSummary2Wrapper afs2 = new AccountFuncdSummary2Wrapper();
       	//object test = AccountFuncdSummary2Wrapper.year();
        
    }
}