var pw_cc_countries = new Object();

pw_cc_countries.countries = {
"Afghanistan" : [],
"Albania" : [],
"Algeria" : [],
"American Samoa" : [],
"Andorra" : [],
"Angola" : [],
"Anguilla" : [],
"Antarctica" : [],
"Antigua and Barbuda" : [],
"Argentina" : [],
"Armenia" : [],
"Aruba" : [],
"Australia" : [],
"Austria" : [],
"Azerbaijan" : [],
"Bahamas" : [],
"Bahrain" : [],
"Bangladesh" : [],
"Barbados" : [],
"Belarus" : [],
"Belgium" : [],
"Belize" : [],
"Benin" : [],
"Bermuda" : [],
"Bhutan" : [],
"Bolivia" : [],
"Bosnia and Herzegovina" : [],
"Botswana" : [],
"Bouvet Island" : [],
"Brazil" : [],
"Brunei Darussalam" : [],
"Bulgaria" : [],
"Burkina Faso" : [],
"Burundi" : [],
"Cambodia" : [],
"Cameroon" : [],
"Canada" : [],
"Cape Verde" : [],
"Cayman Islands" : [],
"Central African Republic" : [],
"Chad" : [],
"Chile" : [],
"China" : [],
"Christmas Island" : [],
"Cocos (keeling) Islands" : [],
"Colombia" : [],
"Comoros" : [],
"Congo" : [],
"Congo, The Democratic Republic of The" : [],
"Cook Islands" : [],
"Costa Rica" : [],
"Croatia" : [],
"Cuba" : [],
"Cyprus" : [],
"Czech Republic" : [],
"Côte D\'ivoire" : [],
"Denmark" : [],
"Djibouti" : [],
"Dominica" : [],
"Dominican Republic" : [],
"Ecuador" : [],
"Egypt" : [],
"El Salvador" : [],
"Equatorial Guinea" : [],
"Eritrea" : [],
"Estonia" : [],
"Ethiopia" : [],
"Falkland Islands (malvinas)" : [],
"Faroe Islands" : [],
"Fiji" : [],
"Finland" : [],
"France" : [],
"French Guiana" : [],
"French Polynesia" : [],
"French Southern Territories" : [],
"Gabon" : [],
"Gambia" : [],
"Georgia" : [],
"Germany" : [],
"Ghana" : [],
"Gibraltar" : [],
"Greece" : [],
"Greenland" : [],
"Grenada" : [],
"Guadeloupe" : [],
"Guam" : [],
"Guatemala" : [],
"Guernsey" : [],
"Guinea" : [],
"Guinea-bissau" : [],
"Guyana" : [],
"Haiti" : [],
"Heard Island and Mcdonald Islands" : [],
"Holy See (vatican City State)" : [],
"Honduras" : [],
"Hong Kong" : [],
"Hungary" : [],
"Iceland" : [],
"India" : [],
"Indonesia" : [],
"Iraq" : [],
"Ireland" : [],
"Isle of Man" : [],
"Israel" : [],
"Italy" : [],
"Jamaica" : [],
"Japan" : [],
"Jersey" : [],
"Jordan" : [],
"Kazakhstan" : [],
"Kenya" : [],
"Kiribati" : [],
"Korea, Republic of" : [],
"Kuwait" : [],
"Kyrgyzstan" : [],
"Lao People\'s Democratic Republic" : [],
"Latvia" : [],
"Lebanon" : [],
"Lesotho" : [],
"Liberia" : [],
"Libyan Arab Jamahiriya" : [],
"Liechtenstein" : [],
"Lithuania" : [],
"Luxembourg" : [],
"Macao" : [],
"Macedonia, The Former Yugoslav Republic" : [],
"Madagascar" : [],
"Malawi" : [],
"Malaysia" : [],
"Maldives" : [],
"Mali" : [],
"Malta" : [],
"Marshall Islands" : [],
"Martinique" : [],
"Mauritania" : [],
"Mauritius" : [],
"Mayotte" : [],
"Mexico" : [],
"Micronesia, Federated States of" : [],
"Moldova, Republic of" : [],
"Monaco" : [],
"Mongolia" : [],
"Montenegro" : [],
"Montserrat" : [],
"Morocco" : [],
"Mozambique" : [],
"Myanmar" : [],
"Namibia" : [],
"Nauru" : [],
"Nepal" : [],
"Netherlands" : [],
"Netherlands Antilles" : [],
"New Caledonia" : [],
"New Zealand" : [],
"Nicaragua" : [],
"Niger" : [],
"Nigeria" : [],
"Niue" : [],
"Norfolk Island" : [],
"Northern Mariana Islands" : [],
"Norway" : [],
"Oman" : [],
"Pakistan" : [],
"Palau" : [],
"Palestinian Territory, Occupied" : [],
"Panama" : [],
"Papua New Guinea" : [],
"Paraguay" : [],
"Peru" : [],
"Philippines" : [],
"Pitcairn" : [],
"Poland" : [],
"Portugal" : [],
"Puerto Rico" : [],
"Qatar" : [],
"Romania" : [],
"Russian Federation" : [],
"Rwanda" : [],
"Réunion" : [],
"Saint Barthélemy" : [],
"Saint Helena" : [],
"Saint Kitts and Nevis" : [],
"Saint Lucia" : [],
"Saint Martin" : [],
"Saint Pierre and Miquelon" : [],
"Saint Vincent and The Grenadines" : [],
"Samoa" : [],
"San Marino" : [],
"Sao Tome and Principe" : [],
"Saudi Arabia" : [],
"Senegal" : [],
"Serbia" : [],
"Seychelles" : [],
"Sierra Leone" : [],
"Singapore" : [],
"Slovakia" : [],
"Slovenia" : [],
"Solomon Islands" : [],
"Somalia" : [],
"South Africa" : [],
"South Georgia and The South Sandwich Isl" : [],
"Spain" : [],
"Sri Lanka" : [],
"Suriname" : [],
"Svalbard and Jan Mayen" : [],
"Swaziland" : [],
"Sweden" : [],
"Switzerland" : [],
"Taiwan, Province of China" : [],
"Tajikistan" : [],
"Tanzania, United Republic of" : [],
"Thailand" : [],
"Timor-leste" : [],
"Togo" : [],
"Tokelau" : [],
"Tonga" : [],
"Trinidad and Tobago" : [],
"Tunisia" : [],
"Turkey" : [],
"Turkmenistan" : [],
"Turks and Caicos Islands" : [],
"Tuvalu" : [],
"Uganda" : [],
"Ukraine" : [],
"United Arab Emirates" : [],
"United Kingdom" : [],
"United States" : [],
"United States Minor Outlying Islands" : [],
"Uruguay" : [],
"Uzbekistan" : [],
"Vanuatu" : [],
"Venezuela, Bolivarian Republic of" : [],
"Viet Nam" : [],
"Virgin Islands, British" : [],
"Virgin Islands, U.s." : [],
"Wallis and Futuna" : [],
"Western Sahara" : [],
"Yemen" : [],
"Zambia" : [],
"Åland Islands" : []
}

pw_cc_countries.Iso31662Codes = {
"AF" : pw_cc_countries.countries["Afghanistan"],
"AL" : pw_cc_countries.countries["Albania"],
"DZ" : pw_cc_countries.countries["Algeria"],
"AS" : pw_cc_countries.countries["American Samoa"],
"AD" : pw_cc_countries.countries["Andorra"],
"AO" : pw_cc_countries.countries["Angola"],
"AI" : pw_cc_countries.countries["Anguilla"],
"AQ" : pw_cc_countries.countries["Antarctica"],
"AG" : pw_cc_countries.countries["Antigua and Barbuda"],
"AR" : pw_cc_countries.countries["Argentina"],
"AM" : pw_cc_countries.countries["Armenia"],
"AW" : pw_cc_countries.countries["Aruba"],
"AU" : pw_cc_countries.countries["Australia"],
"AT" : pw_cc_countries.countries["Austria"],
"AZ" : pw_cc_countries.countries["Azerbaijan"],
"BS" : pw_cc_countries.countries["Bahamas"],
"BH" : pw_cc_countries.countries["Bahrain"],
"BD" : pw_cc_countries.countries["Bangladesh"],
"BB" : pw_cc_countries.countries["Barbados"],
"BY" : pw_cc_countries.countries["Belarus"],
"BE" : pw_cc_countries.countries["Belgium"],
"BZ" : pw_cc_countries.countries["Belize"],
"BJ" : pw_cc_countries.countries["Benin"],
"BM" : pw_cc_countries.countries["Bermuda"],
"BT" : pw_cc_countries.countries["Bhutan"],
"BO" : pw_cc_countries.countries["Bolivia"],
"BA" : pw_cc_countries.countries["Bosnia and Herzegovina"],
"BW" : pw_cc_countries.countries["Botswana"],
"BV" : pw_cc_countries.countries["Bouvet Island"],
"BR" : pw_cc_countries.countries["Brazil"],
"BN" : pw_cc_countries.countries["Brunei Darussalam"],
"BG" : pw_cc_countries.countries["Bulgaria"],
"BF" : pw_cc_countries.countries["Burkina Faso"],
"BI" : pw_cc_countries.countries["Burundi"],
"KH" : pw_cc_countries.countries["Cambodia"],
"CM" : pw_cc_countries.countries["Cameroon"],
"CA" : pw_cc_countries.countries["Canada"],
"CV" : pw_cc_countries.countries["Cape Verde"],
"KY" : pw_cc_countries.countries["Cayman Islands"],
"CF" : pw_cc_countries.countries["Central African Republic"],
"TD" : pw_cc_countries.countries["Chad"],
"CL" : pw_cc_countries.countries["Chile"],
"CN" : pw_cc_countries.countries["China"],
"CX" : pw_cc_countries.countries["Christmas Island"],
"CC" : pw_cc_countries.countries["Cocos (keeling) Islands"],
"CO" : pw_cc_countries.countries["Colombia"],
"KM" : pw_cc_countries.countries["Comoros"],
"CG" : pw_cc_countries.countries["Congo"],
"CD" : pw_cc_countries.countries["Congo, The Democratic Republic of The"],
"CK" : pw_cc_countries.countries["Cook Islands"],
"CR" : pw_cc_countries.countries["Costa Rica"],
"HR" : pw_cc_countries.countries["Croatia"],
"CU" : pw_cc_countries.countries["Cuba"],
"CY" : pw_cc_countries.countries["Cyprus"],
"CZ" : pw_cc_countries.countries["Czech Republic"],
"CI" : pw_cc_countries.countries["Côte D\'ivoire"],
"DK" : pw_cc_countries.countries["Denmark"],
"DJ" : pw_cc_countries.countries["Djibouti"],
"DM" : pw_cc_countries.countries["Dominica"],
"DO" : pw_cc_countries.countries["Dominican Republic"],
"EC" : pw_cc_countries.countries["Ecuador"],
"EG" : pw_cc_countries.countries["Egypt"],
"SV" : pw_cc_countries.countries["El Salvador"],
"GQ" : pw_cc_countries.countries["Equatorial Guinea"],
"ER" : pw_cc_countries.countries["Eritrea"],
"EE" : pw_cc_countries.countries["Estonia"],
"ET" : pw_cc_countries.countries["Ethiopia"],
"FK" : pw_cc_countries.countries["Falkland Islands (malvinas)"],
"FO" : pw_cc_countries.countries["Faroe Islands"],
"FJ" : pw_cc_countries.countries["Fiji"],
"FI" : pw_cc_countries.countries["Finland"],
"FR" : pw_cc_countries.countries["France"],
"GF" : pw_cc_countries.countries["French Guiana"],
"PF" : pw_cc_countries.countries["French Polynesia"],
"TF" : pw_cc_countries.countries["French Southern Territories"],
"GA" : pw_cc_countries.countries["Gabon"],
"GM" : pw_cc_countries.countries["Gambia"],
"GE" : pw_cc_countries.countries["Georgia"],
"DE" : pw_cc_countries.countries["Germany"],
"GH" : pw_cc_countries.countries["Ghana"],
"GI" : pw_cc_countries.countries["Gibraltar"],
"GR" : pw_cc_countries.countries["Greece"],
"GL" : pw_cc_countries.countries["Greenland"],
"GD" : pw_cc_countries.countries["Grenada"],
"GP" : pw_cc_countries.countries["Guadeloupe"],
"GU" : pw_cc_countries.countries["Guam"],
"GT" : pw_cc_countries.countries["Guatemala"],
"GG" : pw_cc_countries.countries["Guernsey"],
"GN" : pw_cc_countries.countries["Guinea"],
"GW" : pw_cc_countries.countries["Guinea-bissau"],
"GY" : pw_cc_countries.countries["Guyana"],
"HT" : pw_cc_countries.countries["Haiti"],
"HM" : pw_cc_countries.countries["Heard Island and Mcdonald Islands"],
"VA" : pw_cc_countries.countries["Holy See (vatican City State)"],
"HN" : pw_cc_countries.countries["Honduras"],
"HK" : pw_cc_countries.countries["Hong Kong"],
"HU" : pw_cc_countries.countries["Hungary"],
"IS" : pw_cc_countries.countries["Iceland"],
"IN" : pw_cc_countries.countries["India"],
"ID" : pw_cc_countries.countries["Indonesia"],
"IQ" : pw_cc_countries.countries["Iraq"],
"IE" : pw_cc_countries.countries["Ireland"],
"IM" : pw_cc_countries.countries["Isle of Man"],
"IL" : pw_cc_countries.countries["Israel"],
"IT" : pw_cc_countries.countries["Italy"],
"JM" : pw_cc_countries.countries["Jamaica"],
"JP" : pw_cc_countries.countries["Japan"],
"JE" : pw_cc_countries.countries["Jersey"],
"JO" : pw_cc_countries.countries["Jordan"],
"KZ" : pw_cc_countries.countries["Kazakhstan"],
"KE" : pw_cc_countries.countries["Kenya"],
"KI" : pw_cc_countries.countries["Kiribati"],
"KR" : pw_cc_countries.countries["Korea, Republic of"],
"KW" : pw_cc_countries.countries["Kuwait"],
"KG" : pw_cc_countries.countries["Kyrgyzstan"],
"LA" : pw_cc_countries.countries["Lao People\'s Democratic Republic"],
"LV" : pw_cc_countries.countries["Latvia"],
"LB" : pw_cc_countries.countries["Lebanon"],
"LS" : pw_cc_countries.countries["Lesotho"],
"LR" : pw_cc_countries.countries["Liberia"],
"LY" : pw_cc_countries.countries["Libyan Arab Jamahiriya"],
"LI" : pw_cc_countries.countries["Liechtenstein"],
"LT" : pw_cc_countries.countries["Lithuania"],
"LU" : pw_cc_countries.countries["Luxembourg"],
"MO" : pw_cc_countries.countries["Macao"],
"MK" : pw_cc_countries.countries["Macedonia, The Former Yugoslav Republic"],
"MG" : pw_cc_countries.countries["Madagascar"],
"MW" : pw_cc_countries.countries["Malawi"],
"MY" : pw_cc_countries.countries["Malaysia"],
"MV" : pw_cc_countries.countries["Maldives"],
"ML" : pw_cc_countries.countries["Mali"],
"MT" : pw_cc_countries.countries["Malta"],
"MH" : pw_cc_countries.countries["Marshall Islands"],
"MQ" : pw_cc_countries.countries["Martinique"],
"MR" : pw_cc_countries.countries["Mauritania"],
"MU" : pw_cc_countries.countries["Mauritius"],
"YT" : pw_cc_countries.countries["Mayotte"],
"MX" : pw_cc_countries.countries["Mexico"],
"FM" : pw_cc_countries.countries["Micronesia, Federated States of"],
"MD" : pw_cc_countries.countries["Moldova, Republic of"],
"MC" : pw_cc_countries.countries["Monaco"],
"MN" : pw_cc_countries.countries["Mongolia"],
"ME" : pw_cc_countries.countries["Montenegro"],
"MS" : pw_cc_countries.countries["Montserrat"],
"MA" : pw_cc_countries.countries["Morocco"],
"MZ" : pw_cc_countries.countries["Mozambique"],
"MM" : pw_cc_countries.countries["Myanmar"],
"NA" : pw_cc_countries.countries["Namibia"],
"NR" : pw_cc_countries.countries["Nauru"],
"NP" : pw_cc_countries.countries["Nepal"],
"NL" : pw_cc_countries.countries["Netherlands"],
"AN" : pw_cc_countries.countries["Netherlands Antilles"],
"NC" : pw_cc_countries.countries["New Caledonia"],
"NZ" : pw_cc_countries.countries["New Zealand"],
"NI" : pw_cc_countries.countries["Nicaragua"],
"NE" : pw_cc_countries.countries["Niger"],
"NG" : pw_cc_countries.countries["Nigeria"],
"NU" : pw_cc_countries.countries["Niue"],
"NF" : pw_cc_countries.countries["Norfolk Island"],
"MP" : pw_cc_countries.countries["Northern Mariana Islands"],
"NO" : pw_cc_countries.countries["Norway"],
"OM" : pw_cc_countries.countries["Oman"],
"PK" : pw_cc_countries.countries["Pakistan"],
"PW" : pw_cc_countries.countries["Palau"],
"PS" : pw_cc_countries.countries["Palestinian Territory, Occupied"],
"PA" : pw_cc_countries.countries["Panama"],
"PG" : pw_cc_countries.countries["Papua New Guinea"],
"PY" : pw_cc_countries.countries["Paraguay"],
"PE" : pw_cc_countries.countries["Peru"],
"PH" : pw_cc_countries.countries["Philippines"],
"PN" : pw_cc_countries.countries["Pitcairn"],
"PL" : pw_cc_countries.countries["Poland"],
"PT" : pw_cc_countries.countries["Portugal"],
"PR" : pw_cc_countries.countries["Puerto Rico"],
"QA" : pw_cc_countries.countries["Qatar"],
"RO" : pw_cc_countries.countries["Romania"],
"RU" : pw_cc_countries.countries["Russian Federation"],
"RW" : pw_cc_countries.countries["Rwanda"],
"RE" : pw_cc_countries.countries["Réunion"],
"BL" : pw_cc_countries.countries["Saint Barthélemy"],
"SH" : pw_cc_countries.countries["Saint Helena"],
"KN" : pw_cc_countries.countries["Saint Kitts and Nevis"],
"LC" : pw_cc_countries.countries["Saint Lucia"],
"MF" : pw_cc_countries.countries["Saint Martin"],
"PM" : pw_cc_countries.countries["Saint Pierre and Miquelon"],
"VC" : pw_cc_countries.countries["Saint Vincent and The Grenadines"],
"WS" : pw_cc_countries.countries["Samoa"],
"SM" : pw_cc_countries.countries["San Marino"],
"ST" : pw_cc_countries.countries["Sao Tome and Principe"],
"SA" : pw_cc_countries.countries["Saudi Arabia"],
"SN" : pw_cc_countries.countries["Senegal"],
"RS" : pw_cc_countries.countries["Serbia"],
"SC" : pw_cc_countries.countries["Seychelles"],
"SL" : pw_cc_countries.countries["Sierra Leone"],
"SG" : pw_cc_countries.countries["Singapore"],
"SK" : pw_cc_countries.countries["Slovakia"],
"SI" : pw_cc_countries.countries["Slovenia"],
"SB" : pw_cc_countries.countries["Solomon Islands"],
"SO" : pw_cc_countries.countries["Somalia"],
"ZA" : pw_cc_countries.countries["South Africa"],
"GS" : pw_cc_countries.countries["South Georgia and The South Sandwich Isl"],
"ES" : pw_cc_countries.countries["Spain"],
"LK" : pw_cc_countries.countries["Sri Lanka"],
"SR" : pw_cc_countries.countries["Suriname"],
"SJ" : pw_cc_countries.countries["Svalbard and Jan Mayen"],
"SZ" : pw_cc_countries.countries["Swaziland"],
"SE" : pw_cc_countries.countries["Sweden"],
"CH" : pw_cc_countries.countries["Switzerland"],
"TW" : pw_cc_countries.countries["Taiwan, Province of China"],
"TJ" : pw_cc_countries.countries["Tajikistan"],
"TZ" : pw_cc_countries.countries["Tanzania, United Republic of"],
"TH" : pw_cc_countries.countries["Thailand"],
"TL" : pw_cc_countries.countries["Timor-leste"],
"TG" : pw_cc_countries.countries["Togo"],
"TK" : pw_cc_countries.countries["Tokelau"],
"TO" : pw_cc_countries.countries["Tonga"],
"TT" : pw_cc_countries.countries["Trinidad and Tobago"],
"TN" : pw_cc_countries.countries["Tunisia"],
"TR" : pw_cc_countries.countries["Turkey"],
"TM" : pw_cc_countries.countries["Turkmenistan"],
"TC" : pw_cc_countries.countries["Turks and Caicos Islands"],
"TV" : pw_cc_countries.countries["Tuvalu"],
"UG" : pw_cc_countries.countries["Uganda"],
"UA" : pw_cc_countries.countries["Ukraine"],
"AE" : pw_cc_countries.countries["United Arab Emirates"],
"GB" : pw_cc_countries.countries["United Kingdom"],
"US" : pw_cc_countries.countries["United States"],
"UM" : pw_cc_countries.countries["United States Minor Outlying Islands"],
"UY" : pw_cc_countries.countries["Uruguay"],
"UZ" : pw_cc_countries.countries["Uzbekistan"],
"VU" : pw_cc_countries.countries["Vanuatu"],
"VE" : pw_cc_countries.countries["Venezuela, Bolivarian Republic of"],
"VN" : pw_cc_countries.countries["Viet Nam"],
"VG" : pw_cc_countries.countries["Virgin Islands, British"],
"VI" : pw_cc_countries.countries["Virgin Islands, U.s."],
"WF" : pw_cc_countries.countries["Wallis and Futuna"],
"EH" : pw_cc_countries.countries["Western Sahara"],
"YE" : pw_cc_countries.countries["Yemen"],
"ZM" : pw_cc_countries.countries["Zambia"],
"AX" : pw_cc_countries.countries["Åland Islands"]
}

pw_cc_countries.Iso31663Codes = {
"AFG" : pw_cc_countries.countries["Afghanistan"],
"ALB" : pw_cc_countries.countries["Albania"],
"DZA" : pw_cc_countries.countries["Algeria"],
"ASM" : pw_cc_countries.countries["American Samoa"],
"AND" : pw_cc_countries.countries["Andorra"],
"AGO" : pw_cc_countries.countries["Angola"],
"AIA" : pw_cc_countries.countries["Anguilla"],
"ATA" : pw_cc_countries.countries["Antarctica"],
"ATG" : pw_cc_countries.countries["Antigua and Barbuda"],
"ARG" : pw_cc_countries.countries["Argentina"],
"ARM" : pw_cc_countries.countries["Armenia"],
"ABW" : pw_cc_countries.countries["Aruba"],
"AUS" : pw_cc_countries.countries["Australia"],
"AUT" : pw_cc_countries.countries["Austria"],
"AZE" : pw_cc_countries.countries["Azerbaijan"],
"BHS" : pw_cc_countries.countries["Bahamas"],
"BHR" : pw_cc_countries.countries["Bahrain"],
"BGD" : pw_cc_countries.countries["Bangladesh"],
"BRB" : pw_cc_countries.countries["Barbados"],
"BLR" : pw_cc_countries.countries["Belarus"],
"BEL" : pw_cc_countries.countries["Belgium"],
"BLZ" : pw_cc_countries.countries["Belize"],
"BEN" : pw_cc_countries.countries["Benin"],
"BMU" : pw_cc_countries.countries["Bermuda"],
"BTN" : pw_cc_countries.countries["Bhutan"],
"BOL" : pw_cc_countries.countries["Bolivia"],
"BIH" : pw_cc_countries.countries["Bosnia and Herzegovina"],
"BWA" : pw_cc_countries.countries["Botswana"],
"BVT" : pw_cc_countries.countries["Bouvet Island"],
"BRA" : pw_cc_countries.countries["Brazil"],
"BRN" : pw_cc_countries.countries["Brunei Darussalam"],
"BGR" : pw_cc_countries.countries["Bulgaria"],
"BFA" : pw_cc_countries.countries["Burkina Faso"],
"BDI" : pw_cc_countries.countries["Burundi"],
"KHM" : pw_cc_countries.countries["Cambodia"],
"CMR" : pw_cc_countries.countries["Cameroon"],
"CAN" : pw_cc_countries.countries["Canada"],
"CPV" : pw_cc_countries.countries["Cape Verde"],
"CYM" : pw_cc_countries.countries["Cayman Islands"],
"CAF" : pw_cc_countries.countries["Central African Republic"],
"TCD" : pw_cc_countries.countries["Chad"],
"CHL" : pw_cc_countries.countries["Chile"],
"CHN" : pw_cc_countries.countries["China"],
"CXR" : pw_cc_countries.countries["Christmas Island"],
"CCK" : pw_cc_countries.countries["Cocos (keeling) Islands"],
"COL" : pw_cc_countries.countries["Colombia"],
"COM" : pw_cc_countries.countries["Comoros"],
"COG" : pw_cc_countries.countries["Congo"],
"COD" : pw_cc_countries.countries["Congo, The Democratic Republic of The"],
"COK" : pw_cc_countries.countries["Cook Islands"],
"CRI" : pw_cc_countries.countries["Costa Rica"],
"HRV" : pw_cc_countries.countries["Croatia"],
"CUB" : pw_cc_countries.countries["Cuba"],
"CYP" : pw_cc_countries.countries["Cyprus"],
"CZE" : pw_cc_countries.countries["Czech Republic"],
"CIV" : pw_cc_countries.countries["Côte D\'ivoire"],
"DNK" : pw_cc_countries.countries["Denmark"],
"DJI" : pw_cc_countries.countries["Djibouti"],
"DMA" : pw_cc_countries.countries["Dominica"],
"DOM" : pw_cc_countries.countries["Dominican Republic"],
"ECU" : pw_cc_countries.countries["Ecuador"],
"EGY" : pw_cc_countries.countries["Egypt"],
"SLV" : pw_cc_countries.countries["El Salvador"],
"GNQ" : pw_cc_countries.countries["Equatorial Guinea"],
"ERI" : pw_cc_countries.countries["Eritrea"],
"EST" : pw_cc_countries.countries["Estonia"],
"ETH" : pw_cc_countries.countries["Ethiopia"],
"FLK" : pw_cc_countries.countries["Falkland Islands (malvinas)"],
"FRO" : pw_cc_countries.countries["Faroe Islands"],
"FJI" : pw_cc_countries.countries["Fiji"],
"FIN" : pw_cc_countries.countries["Finland"],
"FRA" : pw_cc_countries.countries["France"],
"GUF" : pw_cc_countries.countries["French Guiana"],
"PYF" : pw_cc_countries.countries["French Polynesia"],
"ATF" : pw_cc_countries.countries["French Southern Territories"],
"GAB" : pw_cc_countries.countries["Gabon"],
"GMB" : pw_cc_countries.countries["Gambia"],
"GEO" : pw_cc_countries.countries["Georgia"],
"DEU" : pw_cc_countries.countries["Germany"],
"GHA" : pw_cc_countries.countries["Ghana"],
"GIB" : pw_cc_countries.countries["Gibraltar"],
"GRC" : pw_cc_countries.countries["Greece"],
"GRL" : pw_cc_countries.countries["Greenland"],
"GRD" : pw_cc_countries.countries["Grenada"],
"GLP" : pw_cc_countries.countries["Guadeloupe"],
"GUM" : pw_cc_countries.countries["Guam"],
"GTM" : pw_cc_countries.countries["Guatemala"],
"GGY" : pw_cc_countries.countries["Guernsey"],
"GIN" : pw_cc_countries.countries["Guinea"],
"GNB" : pw_cc_countries.countries["Guinea-bissau"],
"GUY" : pw_cc_countries.countries["Guyana"],
"HTI" : pw_cc_countries.countries["Haiti"],
"HMD" : pw_cc_countries.countries["Heard Island and Mcdonald Islands"],
"VAT" : pw_cc_countries.countries["Holy See (vatican City State)"],
"HND" : pw_cc_countries.countries["Honduras"],
"HKG" : pw_cc_countries.countries["Hong Kong"],
"HUN" : pw_cc_countries.countries["Hungary"],
"ISL" : pw_cc_countries.countries["Iceland"],
"IND" : pw_cc_countries.countries["India"],
"IDN" : pw_cc_countries.countries["Indonesia"],
"IRQ" : pw_cc_countries.countries["Iraq"],
"IRL" : pw_cc_countries.countries["Ireland"],
"IMN" : pw_cc_countries.countries["Isle of Man"],
"ISR" : pw_cc_countries.countries["Israel"],
"ITA" : pw_cc_countries.countries["Italy"],
"JAM" : pw_cc_countries.countries["Jamaica"],
"JPN" : pw_cc_countries.countries["Japan"],
"JEY" : pw_cc_countries.countries["Jersey"],
"JOR" : pw_cc_countries.countries["Jordan"],
"KAZ" : pw_cc_countries.countries["Kazakhstan"],
"KEN" : pw_cc_countries.countries["Kenya"],
"KIR" : pw_cc_countries.countries["Kiribati"],
"KOR" : pw_cc_countries.countries["Korea, Republic of"],
"KWT" : pw_cc_countries.countries["Kuwait"],
"KGZ" : pw_cc_countries.countries["Kyrgyzstan"],
"LAO" : pw_cc_countries.countries["Lao People\'s Democratic Republic"],
"LVA" : pw_cc_countries.countries["Latvia"],
"LBN" : pw_cc_countries.countries["Lebanon"],
"LSO" : pw_cc_countries.countries["Lesotho"],
"LBR" : pw_cc_countries.countries["Liberia"],
"LBY" : pw_cc_countries.countries["Libyan Arab Jamahiriya"],
"LIE" : pw_cc_countries.countries["Liechtenstein"],
"LTU" : pw_cc_countries.countries["Lithuania"],
"LUX" : pw_cc_countries.countries["Luxembourg"],
"MAC" : pw_cc_countries.countries["Macao"],
"MKD" : pw_cc_countries.countries["Macedonia, The Former Yugoslav Republic"],
"MDG" : pw_cc_countries.countries["Madagascar"],
"MWI" : pw_cc_countries.countries["Malawi"],
"MYS" : pw_cc_countries.countries["Malaysia"],
"MDV" : pw_cc_countries.countries["Maldives"],
"MLI" : pw_cc_countries.countries["Mali"],
"MLT" : pw_cc_countries.countries["Malta"],
"MHL" : pw_cc_countries.countries["Marshall Islands"],
"MTQ" : pw_cc_countries.countries["Martinique"],
"MRT" : pw_cc_countries.countries["Mauritania"],
"MUS" : pw_cc_countries.countries["Mauritius"],
"MYT" : pw_cc_countries.countries["Mayotte"],
"MEX" : pw_cc_countries.countries["Mexico"],
"FSM" : pw_cc_countries.countries["Micronesia, Federated States of"],
"MDA" : pw_cc_countries.countries["Moldova, Republic of"],
"MCO" : pw_cc_countries.countries["Monaco"],
"MNG" : pw_cc_countries.countries["Mongolia"],
"MNE" : pw_cc_countries.countries["Montenegro"],
"MSR" : pw_cc_countries.countries["Montserrat"],
"MAR" : pw_cc_countries.countries["Morocco"],
"MOZ" : pw_cc_countries.countries["Mozambique"],
"MMR" : pw_cc_countries.countries["Myanmar"],
"NAM" : pw_cc_countries.countries["Namibia"],
"NRU" : pw_cc_countries.countries["Nauru"],
"NPL" : pw_cc_countries.countries["Nepal"],
"NLD" : pw_cc_countries.countries["Netherlands"],
"ANT" : pw_cc_countries.countries["Netherlands Antilles"],
"NCL" : pw_cc_countries.countries["New Caledonia"],
"NZL" : pw_cc_countries.countries["New Zealand"],
"NIC" : pw_cc_countries.countries["Nicaragua"],
"NER" : pw_cc_countries.countries["Niger"],
"NGA" : pw_cc_countries.countries["Nigeria"],
"NIU" : pw_cc_countries.countries["Niue"],
"NFK" : pw_cc_countries.countries["Norfolk Island"],
"MNP" : pw_cc_countries.countries["Northern Mariana Islands"],
"NOR" : pw_cc_countries.countries["Norway"],
"OMN" : pw_cc_countries.countries["Oman"],
"PAK" : pw_cc_countries.countries["Pakistan"],
"PLW" : pw_cc_countries.countries["Palau"],
"PSE" : pw_cc_countries.countries["Palestinian Territory, Occupied"],
"PAN" : pw_cc_countries.countries["Panama"],
"PNG" : pw_cc_countries.countries["Papua New Guinea"],
"PRY" : pw_cc_countries.countries["Paraguay"],
"PER" : pw_cc_countries.countries["Peru"],
"PHL" : pw_cc_countries.countries["Philippines"],
"PCN" : pw_cc_countries.countries["Pitcairn"],
"POL" : pw_cc_countries.countries["Poland"],
"PRT" : pw_cc_countries.countries["Portugal"],
"PRI" : pw_cc_countries.countries["Puerto Rico"],
"QAT" : pw_cc_countries.countries["Qatar"],
"ROU" : pw_cc_countries.countries["Romania"],
"RUS" : pw_cc_countries.countries["Russian Federation"],
"RWA" : pw_cc_countries.countries["Rwanda"],
"REU" : pw_cc_countries.countries["Réunion"],
"BLM" : pw_cc_countries.countries["Saint Barthélemy"],
"SHN" : pw_cc_countries.countries["Saint Helena"],
"KNA" : pw_cc_countries.countries["Saint Kitts and Nevis"],
"LCA" : pw_cc_countries.countries["Saint Lucia"],
"MAF" : pw_cc_countries.countries["Saint Martin"],
"SPM" : pw_cc_countries.countries["Saint Pierre and Miquelon"],
"VCT" : pw_cc_countries.countries["Saint Vincent and The Grenadines"],
"WSM" : pw_cc_countries.countries["Samoa"],
"SMR" : pw_cc_countries.countries["San Marino"],
"STP" : pw_cc_countries.countries["Sao Tome and Principe"],
"SAU" : pw_cc_countries.countries["Saudi Arabia"],
"SEN" : pw_cc_countries.countries["Senegal"],
"SRB" : pw_cc_countries.countries["Serbia"],
"SYC" : pw_cc_countries.countries["Seychelles"],
"SLE" : pw_cc_countries.countries["Sierra Leone"],
"SGP" : pw_cc_countries.countries["Singapore"],
"SVK" : pw_cc_countries.countries["Slovakia"],
"SVN" : pw_cc_countries.countries["Slovenia"],
"SLB" : pw_cc_countries.countries["Solomon Islands"],
"SOM" : pw_cc_countries.countries["Somalia"],
"ZAF" : pw_cc_countries.countries["South Africa"],
"SGS" : pw_cc_countries.countries["South Georgia and The South Sandwich Isl"],
"ESP" : pw_cc_countries.countries["Spain"],
"LKA" : pw_cc_countries.countries["Sri Lanka"],
"SUR" : pw_cc_countries.countries["Suriname"],
"SJM" : pw_cc_countries.countries["Svalbard and Jan Mayen"],
"SWZ" : pw_cc_countries.countries["Swaziland"],
"SWE" : pw_cc_countries.countries["Sweden"],
"CHE" : pw_cc_countries.countries["Switzerland"],
"TWN" : pw_cc_countries.countries["Taiwan, Province of China"],
"TJK" : pw_cc_countries.countries["Tajikistan"],
"TZA" : pw_cc_countries.countries["Tanzania, United Republic of"],
"THA" : pw_cc_countries.countries["Thailand"],
"TLS" : pw_cc_countries.countries["Timor-leste"],
"TGO" : pw_cc_countries.countries["Togo"],
"TKL" : pw_cc_countries.countries["Tokelau"],
"TON" : pw_cc_countries.countries["Tonga"],
"TTO" : pw_cc_countries.countries["Trinidad and Tobago"],
"TUN" : pw_cc_countries.countries["Tunisia"],
"TUR" : pw_cc_countries.countries["Turkey"],
"TKM" : pw_cc_countries.countries["Turkmenistan"],
"TCA" : pw_cc_countries.countries["Turks and Caicos Islands"],
"TUV" : pw_cc_countries.countries["Tuvalu"],
"UGA" : pw_cc_countries.countries["Uganda"],
"UKR" : pw_cc_countries.countries["Ukraine"],
"ARE" : pw_cc_countries.countries["United Arab Emirates"],
"GBR" : pw_cc_countries.countries["United Kingdom"],
"USA" : pw_cc_countries.countries["United States"],
"UMI" : pw_cc_countries.countries["United States Minor Outlying Islands"],
"URY" : pw_cc_countries.countries["Uruguay"],
"UZB" : pw_cc_countries.countries["Uzbekistan"],
"VUT" : pw_cc_countries.countries["Vanuatu"],
"VEN" : pw_cc_countries.countries["Venezuela, Bolivarian Republic of"],
"VNM" : pw_cc_countries.countries["Viet Nam"],
"VGB" : pw_cc_countries.countries["Virgin Islands, British"],
"VIR" : pw_cc_countries.countries["Virgin Islands, U.s."],
"WLF" : pw_cc_countries.countries["Wallis and Futuna"],
"ESH" : pw_cc_countries.countries["Western Sahara"],
"YEM" : pw_cc_countries.countries["Yemen"],
"ZMB" : pw_cc_countries.countries["Zambia"],
"ALA" : pw_cc_countries.countries["Åland Islands"]
}