public with sharing class DealList {
	 
	
	     
public static testMethod void testMe(   )
      {
      bTesting=true;
      DealList x = new DealList();
      
      x.DummyMethod();
      
      }
 
  
 public static boolean bTesting = false;

 public string DummyMethod()
 {
 string s = '1213';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
 s='abc';
return s;
 }
    
}