/**
 * Auto Generated and Deployed by the Declarative Lookup Rollup Summaries Tool package (dlrs)
 **/
@IsTest
private class dlrs_External_Working_Group_MemberTest
{
    @IsTest
    private static void testTrigger()
    {
        // Force the dlrs_External_Working_Group_Mea0KTrigger to be invoked, fails the test if org config or other Apex code prevents this.
        dlrs.RollupService.testHandler(new External_Working_Group_Member__c());
    }
}